# Generated by Django 5.2.6 on 2025-09-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
    ]
