# Generated by Django 5.2.6 on 2025-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_downvotes_remove_project_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
